/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author UMAM
 */
public class ProfilUser extends javax.swing.JFrame {

    /**
     * Creates new form ProfilUser
     */
    public ProfilUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Rekening = new javax.swing.JLabel();
        BirthDay = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        Profil = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(997, 744));
        setPreferredSize(new java.awt.Dimension(997, 711));

        jPanel1.setPreferredSize(new java.awt.Dimension(1980, 1080));
        jPanel1.setLayout(null);

        Rekening.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Rekening.setText("1122334455667788");
        jPanel1.add(Rekening);
        Rekening.setBounds(34, 530, 410, 30);

        BirthDay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BirthDay.setText("11-november-2021");
        jPanel1.add(BirthDay);
        BirthDay.setBounds(34, 640, 410, 30);

        Password.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Password.setText("1234");
        jPanel1.add(Password);
        Password.setBounds(504, 240, 400, 30);

        Email.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Email.setText("Warteg@gmail.com");
        jPanel1.add(Email);
        Email.setBounds(504, 354, 400, 30);

        PhoneNumber.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PhoneNumber.setText("+62 82282101020");
        jPanel1.add(PhoneNumber);
        PhoneNumber.setBounds(504, 460, 400, 40);

        Address.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Address.setText("Jl.Syiah Kuala");
        jPanel1.add(Address);
        Address.setBounds(499, 580, 410, 30);

        Username.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Username.setText("Warung Teknologi");
        jPanel1.add(Username);
        Username.setBounds(498, 124, 410, 40);

        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/github.png"))); // NOI18N
        jPanel1.add(Foto);
        Foto.setBounds(60, 110, 350, 340);

        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Profil.png"))); // NOI18N
        jPanel1.add(Profil);
        Profil.setBounds(-30, -10, 997, 711);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(620, 640, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        new HalamanAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel BirthDay;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel Profil;
    private javax.swing.JLabel Rekening;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
